// ======================================================
// HISTORY CONSTANTS
// Owns all behavioral event type identifiers
// Every lifecycle event that must be remembered lives here
// Phase 2.3: Extended for challenges, social, hubs, trust, rewards
// ======================================================

const BEHAVIORAL_EVENT_TYPES = {
  // Mission events
  MISSION_CREATED: 'MISSION_CREATED',
  MISSION_COMPLETED: 'MISSION_COMPLETED',
  MISSION_FAILED: 'MISSION_FAILED',
  MISSION_CANCELLED: 'MISSION_CANCELLED',
  MISSION_EXPIRED: 'MISSION_EXPIRED',

  // Discipline events
  DISCIPLINE_ENABLED: 'DISCIPLINE_ENABLED',
  DISCIPLINE_DISABLED: 'DISCIPLINE_DISABLED',
  DISCIPLINE_COMPLETED: 'DISCIPLINE_COMPLETED',
  DISCIPLINE_FAILED: 'DISCIPLINE_FAILED',
  DAILY_RESET: 'DAILY_RESET',

  // Player events
  ONBOARDING_COMPLETED: 'ONBOARDING_COMPLETED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',

  // Progression events
  STREAK_CHANGED: 'STREAK_CHANGED',
  LEVEL_UP: 'LEVEL_UP',
  XP_GAINED: 'XP_GAINED',
  XP_LOST: 'XP_LOST',

  // Phase 2.3 — Challenge events
  CHALLENGE_CREATED: 'CHALLENGE_CREATED',
  CHALLENGE_JOINED: 'CHALLENGE_JOINED',
  CHALLENGE_SUBMITTED: 'CHALLENGE_SUBMITTED',
  CHALLENGE_WON: 'CHALLENGE_WON',
  CHALLENGE_LOST: 'CHALLENGE_LOST',
  CHALLENGE_CANCELLED: 'CHALLENGE_CANCELLED',
  CHALLENGE_EXPIRED: 'CHALLENGE_EXPIRED',
  // Phase 3.1.6 — Participation lifecycle
  CHALLENGE_INVITED: 'CHALLENGE_INVITED',
  CHALLENGE_ACCEPTED: 'CHALLENGE_ACCEPTED',
  CHALLENGE_DECLINED: 'CHALLENGE_DECLINED',
  CHALLENGE_LEFT: 'CHALLENGE_LEFT',

  // Phase 2.3 — Social events
  FRIEND_REQUEST_SENT: 'FRIEND_REQUEST_SENT',
  FRIEND_REQUEST_ACCEPTED: 'FRIEND_REQUEST_ACCEPTED',
  FRIEND_REQUEST_DECLINED: 'FRIEND_REQUEST_DECLINED',
  FRIENDSHIP_ENDED: 'FRIENDSHIP_ENDED',

  // Phase 2.3 — Hub events
  HUB_CREATED: 'HUB_CREATED',
  HUB_JOINED: 'HUB_JOINED',
  HUB_LEFT: 'HUB_LEFT',

  // Phase 2.3 — Trust events
  TRUST_SCORE_CHANGED: 'TRUST_SCORE_CHANGED',
  TRUST_TIER_CHANGED: 'TRUST_TIER_CHANGED',

  // Phase 2.3 — Reward events
  REWARD_CLAIMED: 'REWARD_CLAIMED',
  REWARD_REDEEMED: 'REWARD_REDEEMED',
  REWARD_EXPIRED: 'REWARD_EXPIRED'
};

module.exports = {
  BEHAVIORAL_EVENT_TYPES
};

